server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: #用户名
    password: #密码
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  #腾讯云对象存储API密钥secretId
  qcloud:
    secretId: 密钥id
    #API密钥secretKey
    secretKey: 密钥
    #存储桶所属地域
    region: ap-nanjing
    #存储桶空间名称
    bucketName: 存储桶名称
    #存储桶访问域名
    url: https://pimg-1310724460.cos.ap-nanjing.myqcloud.com
    #上传文件前缀路径(eg:/images/)
    prefix: 前缀
mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
  type-aliases-package: com.example.myitem.entity

